CREATE TABLE PRODUCTS (
	PRODUCT_ID SERIAL PRIMARY KEY,
	PRODUCT_NAME VARCHAR(50),
	DESCRIPTION TEXT,
	PRICE NUMERIC,
	QUANTITY_IN_STOCK INTEGER
);

CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	USER_NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	REGISTRATION_DATE DATE
);

CREATE TABLE ORDERS (
	ORDER_ID SERIAL PRIMARY KEY,
	USER_ID INTEGER,
	ORDER_DATE DATE,
	STATUS VARCHAR(20),
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE ORDER_DETAILS (
	ORDER_DETAIL_ID SERIAL PRIMARY KEY,
	ORDER_ID INTEGER,
	PRODUCT_ID INTEGER,
	QUANTITY INTEGER,
	TOTAL_COST NUMERIC,
	FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID) ON DELETE CASCADE
);